application_settings:
  port: 8000
log_settings:
  log_dir: logs
  targets:
    - kind: stdout
      level: debug
    - kind: file
      level: info
      filename: info.log
      rotation: daily
    - kind: file
      level: error
      filename: error.log
      rotation: daily
db_settings:
  host: 127.0.0.1
  port: 5432
  database: kuai_saver
  username: postgres
  password: password