application:
  port: 8000
  pdd:
    domain: https://gw-api.pinduoduo.com/api/router
    api_good_search: pdd.ddk.goods.search
    api_gen_short_url: pdd.ddk.goods.zs.unit.url.gen
    api_order_detail: pdd.ddk.order.detail.get

log:
  log_dir: logs
  targets:
    - kind: stdout
      level: debug
    - kind: file
      level: info
      filename: info.log
      rotation: daily
    - kind: file
      level: error
      filename: error.log
      rotation: daily
db:
  host: 127.0.0.1
  port: 5432
  database: kuai_saver
  username: postgres
  password: password
